[package]
name = "nostr"
version = "0.4.1"
edition = "2021"
description = "Rust implementation of the Nostr protocol."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/nostr-rs-sdk"
repository = "https://github.com/yukibtc/nostr-rs-sdk.git"
license = "MIT"
readme = "README.md"
rust-version = "1.64"
keywords = ["nostr", "protocol", "sdk", "rust"]

[features]
default = ["nip06"]
nip06 = ["bip32"]

[dependencies]
aes = "0.8"
anyhow = "1.0"
base64 = "0.13"
bech32 = "0.9"
bip32 = { version = "0.4", optional = true }
bitcoin_hashes = { version = "0.11", features = ["serde"] }
cbc = { version = "0.1", features = ["alloc"] }
log = "0.4"
once_cell = "1"
regex = "1.7"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls-webpki-roots", "socks"]}
secp256k1 = { version = "0.24", features = ["rand", "rand-std", "serde", "bitcoin_hashes"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
thiserror = "1.0"
url = "2"
uuid = { version = "1.2", features = ["serde"] }

[dev-dependencies]
csv = "1.1.5"
env_logger = "0.8.2"
tungstenite = { version = "0.17", features = ["rustls-tls-webpki-roots"]}

[[example]]
name = "nip06"
required-features = ["nip06"]
