[package]
name = "nostr"
version = "0.9.0"
edition = "2021"
description = "Rust implementation of the Nostr protocol."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "protocol", "sdk", "rust"]

[features]
default = ["all-nips"]
all-nips = ["nip04", "nip05", "nip06", "nip11"]
nip04 = ["dep:aes", "dep:base64", "dep:cbc"]
nip05 = ["dep:reqwest"]
nip06 = ["dep:bip39"]
nip11 = ["dep:reqwest"]
blocking = ["reqwest?/blocking"]

[dependencies]
aes = { version = "0.8", optional = true }
base64 = { version = "0.13", optional = true }
bip39 = { version = "1.0", optional = true }
bitcoin = { version = "0.29", features = ["rand", "serde"] }
cbc = { version = "0.1", features = ["alloc"], optional = true }
log = "0.4"
once_cell = "1"
regex = "1.7"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls-webpki-roots", "socks"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
thiserror = "1.0"
url = { version = "2", features = ["serde"] }

[dev-dependencies]
csv = "1.1.5"
env_logger = "0.8.2"
tungstenite = { version = "0.17", features = ["rustls-tls-webpki-roots"] }

[[example]]
name = "nip04"
required-features = ["nip04"]

[[example]]
name = "nip05"
required-features = ["nip05", "blocking"]

[[example]]
name = "nip06"
required-features = ["nip06"]

[[example]]
name = "nip11"
required-features = ["nip11", "blocking"]
