[workspace]
members = [
    "bindings/nostr-sdk-ffi",
    "crates/*",
]
default-members = ["crates/*"]

[workspace.package]
edition = "2021"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
license = "MIT"
homepage = "https://github.com/p2kishimoto/nostr-rs-sdk"
repository = "https://github.com/p2kishimoto/nostr-rs-sdk.git"
rust-version = "1.64"

[profile.release]
lto = true
codegen-units = 1