[package]
name = "nostr-rs"
version = "0.1.0"
authors = ["Paul Miller <paul@pauljmiller.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin_hashes = { version = "0.9.4", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
env_logger = "0.8.2"
secp256k1 = { version = "0.20.1", features = ["rand", "rand-std", "serde", "bitcoin_hashes"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
serde_repr = "0.1.6"
thiserror = "1.0.23"
tungstenite = "0.12.0"
url = "2.2.0"
