[package]
name = "nostr-ffi"
version = "0.1.0"
edition = "2021"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
keywords = ["nostr", "rust", "ffi"]

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
nostr  = { path = "../../crates/nostr" }
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "b50a66fb95ca1f9cf69b25e020f7c3382c0ce528" }
uniffi_macros = { git = "https://github.com/mozilla/uniffi-rs", rev = "b50a66fb95ca1f9cf69b25e020f7c3382c0ce528" }

[build-dependencies]
uniffi_build = { git = "https://github.com/mozilla/uniffi-rs", rev = "b50a66fb95ca1f9cf69b25e020f7c3382c0ce528", features = ["builtin-bindgen"] }
