[package]
name = "nostr-ffi"
version = "0.1.0"
edition = "2021"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/nostr-rs-sdk"
repository = "https://github.com/yukibtc/nostr-rs-sdk.git"
license = "MIT"
rust-version = "1.64"
keywords = ["nostr", "rust", "ffi"]

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
nostr  = { path = "../../crates/nostr", features = ["all-nips"] }
uniffi = "0.21.0"
uniffi_macros = "0.21.0"

[build-dependencies]
uniffi_build = { version = "0.21.0", features = ["builtin-bindgen"] }
