[package]
name = "nostr-sdk"
version = "0.2.0"
edition = "2021"
description = "High level Nostr client library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/nostr-rs-sdk"
repository = "https://github.com/yukibtc/nostr-rs-sdk.git"
license = "MIT"
readme = "README.md"
rust-version = "1.64"
keywords = ["nostr", "sdk", "rust"]

[features]
default = []
blocking = ["once_cell"]

[dependencies]
anyhow = "1"
bitcoin_hashes = { version = "0.11", features = ["serde"] }
futures-util = "0.3"
log = "0.4"
nostr = { version = "0.3.0", path = "../nostr" }
once_cell = { version = "1", optional = true }
tokio = { version = "1", features = ["full"] }
tokio-socks = "0.5"
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-webpki-roots"] }
url = "2"
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }

[dev-dependencies]
env_logger = "0.8"

[[example]]
name = "client"

[[example]]
name = "client_blocking"
required-features = ["blocking"]