[package]
name = "nostr-sdk"
version = "0.7.1"
edition = "2021"
description = "High level Nostr client library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/nostr-rs-sdk"
repository = "https://github.com/yukibtc/nostr-rs-sdk.git"
license = "MIT"
readme = "README.md"
rust-version = "1.64"
keywords = ["nostr", "sdk", "rust"]

[features]
default = []
blocking = ["dep:once_cell"]
all-nips = ["nostr/all-nips"]
nip04 = ["nostr/nip04"]
nip06 = ["nostr/nip06"]

[dependencies]
futures-util = "0.3"
log = "0.4"
nostr = { version = "0.7.1", path = "../nostr" }
once_cell = { version = "1", optional = true }
tokio = { version = "1", features = ["full"] }
tokio-socks = "0.5"
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-webpki-roots"] }
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }

[dev-dependencies]
env_logger = "0.8"

[[example]]
name = "client"
required-features = ["all-nips"]

[[example]]
name = "client_blocking"
required-features = ["all-nips", "blocking"]