[package]
name = "nostr-sdk"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
blocking = ["once_cell"]

[dependencies]
anyhow = "1"
bitcoin_hashes = { version = "0.11", features = ["serde"] }
futures-util = "0.3"
log = "0.4"
nostr-sdk-base = { path = "../nostr-sdk-base" }
nostr-sdk-common = { path = "../nostr-sdk-common" }
once_cell = { version = "1", optional = true }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.17", features = ["rustls-tls-webpki-roots"] }
url = "2"
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }

[dev-dependencies]
chrono = "0.4"
env_logger = "0.8"

[[example]]
name = "client"

[[example]]
name = "client_blocking"
required-features = ["blocking"]