[package]
name = "nostr-sdk"
version = "0.8.1"
edition = "2021"
description = "High level Nostr client library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "sdk", "rust"]

[features]
default = ["all-nips"]
blocking = ["dep:once_cell"]
all-nips = ["nostr/all-nips"]
nip04 = ["nostr/nip04"]
nip06 = ["nostr/nip06"]

[dependencies]
futures-util = "0.3"
log = "0.4"
nostr = { version = "0.8", path = "../nostr" }
once_cell = { version = "1", optional = true }
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.23.4"
tokio-socks = "0.5"
tokio-tungstenite = { version = "0.18", features = ["rustls-tls-webpki-roots"] }
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }
webpki-roots = "0.22.6"

[dev-dependencies]
env_logger = "0.8"

[[example]]
name = "client"
required-features = ["all-nips"]

[[example]]
name = "client_blocking"
required-features = ["all-nips", "blocking"]