[package]
version = "0.0.0"
edition = "2021"
name = "nostr-nodejs"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
napi = { version = "2.10", default-features = false, features = ["napi4"] }
napi-derive = "2.10"
nostr = { path = "../../crates/nostr" }

[build-dependencies]
napi-build = "2.0"
